GymCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gymapp.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gymapp/urls.py
from django.urls import path
from gymapp import views


app_name = "gymapp"

urlpatterns = [
    #Homepage
    path("", views.base, name='base'),

    #Prodotti
    path('manubri/', views.manubri, name='manubri'),
    path('bilancieri/', views.bilancieri, name='bilancieri'),
    path('dischi/', views.dischi, name='dischi'),
    path('collari/', views.collari, name='collari'),
    path('tapisrulant/', views.tapis, name='tapis'),
    path('vogatori/', views.vogatori, name='vogatori'),
    path('cyclette/', views.bike, name='cyclette'),
    path('unica/', views.unica, name='unica'),
    path('rack/', views.rack, name='rack' ),
    path('addome/', views.addome, name='addome'),
    path('lombare/', views.lombare, name='lombare'),
    path('panche/', views.panche, name='panche'),
    path('dettagli_prodotto/<pid>/', views.product_detail_view, name ='dettagli_prodotto'),

    #Menù
    path('contatti/', views.contatti, name='contatti'),  
    path('search/', views.search, name='search'),

    #Privacy
    path('privacy/', views.privacy, name='privacy'),

    #Fornitore
    path('fornitore/<vid>/', views.fornitore_list, name ='fornitore_list'),

    #Aggiungi Recensione
    path('product/<int:pid>/', views.product_detail_view, name='product_details'),

    #Carrello
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:pid>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:pk>/', views.update_cart_item, name='update_cart_item'),
    path('cart/remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),

    #Checkout
    path('checkout/', views.checkout_view, name='checkout'),

    #Pagamento
    path('payment_completed/', views.payment_completed_view, name='payment_completed'),
    path('payment_failed/', views.payment_failed_view, name='payment_failed'),


]



useradmin/urls.py
from django.urls import path
from useradmin import views

app_name = "useradmin"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("products/", views.products, name="products"),
    path("add_product/", views.add_product, name="add_product"),
    path("edit_product/<pid>/", views.edit_product, name="edit_product"),
    path("delete_product/<pid>/", views.delete_product, name="delete_product"),
    path("manage-users/", views.manage_users_view, name="manage_users"),

    path('fornitore/', views.fornitore_view, name='fornitore-view'),
    path('fornitore/modifica/', views.fornitore_update, name='fornitore-update'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("user-view/", views.user_view, name="user-view"),

    path("profile/edit/", views.profile_update, name="profile-update"),

]

gymapp/models.py
from django.db import models
from django.conf import settings
from shortuuid.django_fields import ShortUUIDField
from userauths.models import User
from django.utils.html import mark_safe
from unicodedata import decimal

# Definisce insiemi di opzioni predefinite per i campi dei modelli Django, 
# utilizzati per gestire lo stato degli ordini, la visibilità dei prodotti, 
# le valutazioni degli utenti e le categorie di articoli

STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)


STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)

CATEGORY = (
    ("manubrio", "Manubrio"),
    ("panca", "Panca"),
    ("bike", "Bike"),
    ("bilanciere", "Bilanciere"),
    ("collare", "Collare"),
    ("disco", "Disco"),
    ("lombare", "Lombare"),
    ("rack", "Rack"),
    ("tapisrulant", "TapisRulant"),
    ("unica", "Unica"),
    ("vogatore", "Vogatore"),
    ("addome", "Addome"),
)



# Genera il percorso di salvataggio per i file caricati dagli utenti, 
# organizzandoli in cartelle con il loro ID utente
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

# Modello per le categorie dei prodotti, con un identificatore univoco personalizzato, 
# titolo, immagine e un metodo per visualizzare un'anteprima dell'immagine nell'admin di Django
class Category(models.Model):

    cid  = ShortUUIDField(unique=True, length= 10, max_length=20, prefix ="cat", alphabet = "abcdefgh12345")
    
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="category")

    # Imposta il nome plurale per il modello nell'admin di Django
    class Meta:
        verbose_name_plural = "Categories"

    # Restituisce un'anteprima dell'immagine come HTML, utile per l'admin di Django
    def category_image(self):
        return mark_safe ('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    # Rappresentazione testuale dell'oggetto, restituisce il titolo della categoria
    def __str__(self):
        return self.title


# Modello per i fornitori, con un identificatore univoco personalizzato, informazioni di contatto, 
# valutazioni e un'anteprima dell'immagine nell'admin di Django
class Fornitore(models.Model):
    vid  = ShortUUIDField(unique=True, length= 10, max_length=20, prefix ="forn", alphabet = "abcdefgh12345")
    
    title = models.CharField(max_length=200, default ="Nestify")
    image = models.ImageField(upload_to= user_directory_path)
    description = models.TextField(null= True, blank=True)

    address = models.CharField(max_length=200, default="123 Via Emilia")
    contact = models.CharField(max_length=200, default="+123 (059) 798")
    chat_resp_time = models.CharField(max_length=200, default="100")
    spedizione_in_tempo = models.CharField(max_length=200, default="100")
    valutazione_autentica = models.CharField(max_length=200, default="100")
    days_return = models.CharField(max_length=200, default="100")
    periodo_rimborso = models.CharField(max_length=200, default="100")


    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Fornitori"
    
    def fornitore_image(self):
        return mark_safe ('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title


# Modello per la gestione dei prodotti, con identificatore univoco,collegamenti a utente, 
# categoria e fornitore, dettagli sul prodotto,disponibilità, stato e informazioni di catalogazione
class Product(models.Model):
    pid = ShortUUIDField(unique=True, length= 10, max_length=30, alphabet = "abcdefgh12345")
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    categoria = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    vendor = models.ForeignKey(Fornitore, on_delete=models.SET_NULL, null=True, related_name="vendor")
    

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=user_directory_path)
    description = models.TextField(null= True, blank=True)
    
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")

    specifications= models.TextField(null=True, blank=True)
    stock_count = models.CharField(max_length=100, default="10")
    

    product_status = models.CharField(choices= STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)


    categ_type = models.CharField(choices=CATEGORY, max_length=40, default="manubrio")


    sku = ShortUUIDField(unique=True, length= 4, max_length=10, prefix ="sku", alphabet = "1234567890")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)


    class Meta:
        verbose_name_plural = "Prodotti"

    def product_image(self):
        return mark_safe ('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title

# Modello per la gestione delle immagini aggiuntive dei prodotti, 
# consentendo il caricamento di più immagini per un singolo prodotto
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = "Product Images"


####################################### Cart, Order, Order Items and Adress #################################################################
####################################### Cart, Order, Order Items and Adress #################################################################
####################################### Cart, Order, Order Items and Adress #################################################################
####################################### Cart, Order, Order Items and Adress #################################################################
####################################### Cart, Order, Order Items and Adress #################################################################


# Modello per la gestione degli ordini nel carrello, includendo l'utente, 
# il prezzo totale, lo stato del pagamento e la data dell'ordine
class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices= STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural = "Cart Order"

# Modello per la gestione degli articoli all'interno di un ordine, 
# collegando ogni prodotto all'ordine, includendo dettagli come quantità, prezzo, totale e un'anteprima dell'immagine
class CartOrderItem(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True, blank=True)  # Collega al prodotto
    invoice_no = models.CharField(max_length=200) # Numero di fattura associato all'ordine
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")


    class Meta:
        verbose_name_plural = "Cart Items"

    def order_img(self):
        return mark_safe ('<img src="/media/%s" width="50" height="50" />' % (self.image))


####################################### Product Review, address #################################################################
####################################### Product Review, address #################################################################
####################################### Product Review, address #################################################################

# Modello per la gestione delle recensioni sui prodotti, includendo l'utente, il prodotto recensito, 
# il testo della recensione, la valutazione e la data di creazione
class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True)
    product =  models.ForeignKey(Product, on_delete=models.SET_NULL, null= True, related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"

    def __str__(self):
        if self.product:
            return self.product.title
        return "Recensione senza prodotto associato"
    
    # Restituisce la valutazione della recensione
    def get_rating(self):
        return self.rating
    
# Modello per la gestione degli indirizzi degli utenti, includendo l'utente associato, 
# l'indirizzo e un indicatore di stato
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True)
    address = models.CharField(max_length=200, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"


# Modello per la gestione delle recensioni dei fornitori, collegando ogni recensione 

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}E-commerce Attrezzatura da Palestra{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/homepage_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/dettagli_prodotto_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/fornitore_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/search_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/checkout_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/payment_failed.css' %}">
    <link rel="stylesheet" href="{% static 'css/payment_completed.css' %}">
    <link rel="stylesheet" href="{% static 'css/recc.css' %}">
</head>
<script>
    // Chiude automaticamente i messaggi di allerta dopo 3 secondi
    setTimeout(() => {
        let alertElements = document.querySelectorAll('.alert');
        alertElements.forEach(alert => {
            alert.classList.remove('show');
            alert.classList.add('fade');
            setTimeout(() => alert.remove(), 500);
        });
    }, 3000);
</script>
<body>
    <header>
        <div class="logo-container">
            <a href ="{% url 'gymapp:base' %}">
            <img src="{% static 'media/logo.jpg' %}" alt="Logo GymShop" class="logo"></a>
            <h1>GymShop</h1>
        </div>
        <form action="{% url 'gymapp:search' %}" method="get" style="margin: 0 auto; max-width: 400px; display: flex;">
            <input type="text" name="q" placeholder="Cerca prodotti..." style="flex: 1; padding: 0.5rem; border: 1px solid #ccc; border-radius: 5px 0 0 5px;">
            <button type="submit" style="padding: 0.5rem 1rem; background: #333; color: #fff; border: none; border-radius: 0 5px 5px 0; cursor: pointer;">
                Cerca🔍
            </button>
        </form>
        <nav>
            <ul>
                <li class="dropdown">
                    <a href="" class="dropbtn">Utente👤</a>
                    <ul class="dropdown-content">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                        <li><a href="{% url 'userauths:user-view' %}">Profilo</a></li>
                            {% if request.user.is_fornitore %}
                            <li><a href="{% url 'useradmin:dashboard' %}">Dashboard</a></li>
                            {% endif %}
                        {% else %}
                        <li><a href="{% url 'userauths:sign-up' %}">Registrati</a></li>
                        <li><a href="{% url 'userauths:sign-in' %}">Accedi</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li><a href="{% url 'gymapp:cart' %}">Carrello🛒</a></li>
                <li><a href="{% url 'gymapp:contatti' %}">Contattaci👥</a></li>
            </ul>
        </nav>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <!-- menù a tendina --> 
    <section class="menu">
        <nav>
            <ul class="menu">
                <li class="dropdown">
                    <a href="" class="dropbtn">Pesistica🏋</a>
                    <ul class="dropdown-content">
                        <li><a href="{% url 'gymapp:manubri' %}">Manubri</a></li>
                        <li><a href="{% url 'gymapp:panche' %}">Panche</a></li>
                        <li><a href="{% url 'gymapp:bilancieri' %}">Bilancieri Olimpici</a></li>
                        <li><a href="{% url 'gymapp:dischi' %}">Dischi Olimpici</a></li>
                        <li><a href="{% url 'gymapp:collari' %}">Collari Olimpici</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href= "" class="dropbtn">Cardio🚴</a>
                    <ul class="dropdown-content">
                        <li><a href="{% url 'gymapp:tapis' %}">TapisRulant</a></li>
                        <li><a href="{% url 'gymapp:vogatori' %}">Vogatori</a></li>
                        <li><a href="{% url 'gymapp:cyclette' %}">Cyclette</a></li>
                    </ul>
                    <li class="dropdown">
                        <a href= "" class="dropbtn">Multigym🦾</a>
                        <ul class="dropdown-content">
                            <li><a href="{% url 'gymapp:unica' %}">Unica</a></li>
                            <li><a href="{% url 'gymapp:rack' %}">Rack</a></li>
                            <li><a href="{% url 'gymapp:addome' %}">Addominiali</a></li>
                            <li><a href="{% url 'gymapp:lombare' %}">Lombare</a></li>
                        </ul>
            </ul>
        </nav>
    </section>  
    <section class="hero">
        <h2>{% block hero_title %}Attrezzatura da palestra di alta qualità{% endblock %}</h2>
    </section>

    {% block hero_image %}
    <section class="copertina-container">
        <img src="/media/back.jpg" alt="copertina GymShop" class="copertina"></a>
    </section>
    {% endblock %}
    
    <section class="products">
        {% block products %}
        {% if user.is_authenticated %}
            <section class="recommended">
                <h2>Prodotti per te</h2>
                {% if recommended_products %}
                <div class="product-list">
                    {% for product in recommended_products %}
                    <div class="card">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                        <h3>{{ product.title }}</h3>
                        <p>Prezzo: €{{ product.price }}</p>
                        <a href="{% url 'gymapp:dettagli_prodotto' product.pid %}">Visualizza Dettagli</a>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                    <p>Non ci sono prodotti consigliati al momento.</p>
                {% endif %}
            </section>
        {% else %}
            <section class="login-prompt">
                <p class="login-message">Devi effettuare il login per vedere le recensioni.</p>
                <a href="{% url 'userauths:sign-in' %}" class="login-button">Effettua il Login</a>
            </section>
        {% endif %}
        {% endblock %}
    </section>

    <section class="contact">
        {% block content %}
        <!-- Contenuto dei contatti inserito nei template figli -->
        {% endblock %}
    </section>

    <footer>
        <p>&copy; 2024 GymShop - Tutti i diritti riservati</p>
        <p><a href="{% url 'gymapp:privacy' %}">informativa e privacy</a></p>
    </footer>
</body>
</html>

templates/partials/cart.html
{% extends 'partials/base.html' %}
{% block title %}Carrello 🛒{% endblock %}
{% block hero_title %}Carrello 🛒{% endblock %}
{% block hero_image %}
<!-- Nessuna immagine -->
{% endblock %}
{% block products %}
<!-- Nessuna Prodotto -->
{% endblock %}
{% block content %}
{% if cart_items %}
<table class="cart-table">
    <thead>
        <tr>
            <th>Prodotto</th>
            <th>Immagine</th>
            <th>Quantità</th>
            <th>Prezzo Unitario</th>
            <th>Totale</th>
            <th>Azioni</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart_items %}
            <tr>
                <td>{{ item.product.title }}</td>
                <td>
                    <a href="{% url 'gymapp:dettagli_prodotto' item.product.pid %}"><img src="{{ item.product.image.url }}" alt="{{ item.product.title }}" class="product-image" style="max-width: 100px;"></a>
                </td>
                <td>
                    <form method="POST" action="{% url 'gymapp:update_cart_item' item.pk %}">
                        {% csrf_token %}
                        <input type="number" name="quantity" value="{{ item.qty }}" min="1" class="quantity-input">
                        <button type="submit" class="update-btn">Aggiorna</button>
                    </form>
                </td>
                <td>€{{ item.product.price }}</td>
                <td>€{{ item.total }}</td>
                <td>
                    <a href="{% url 'gymapp:remove_from_cart' item.pk %}" class="remove-btn">Rimuovi</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<h3>Totale Carrello: €{{ total|floatformat:2 }}</h3>
<!-- Bottone per il checkout -->
<div class="checkout-button-container">
    <a href="{% url 'gymapp:base' %}" class="btn return-btn">Continua lo shopping</a>
    <a href="{% url 'gymapp:checkout' %}" class="btn checkout-btn">Vai al Checkout</a>
</div>
{% else %}
<!-- Messaggio per carrello vuoto -->
<h3>Il tuo carrello è vuoto</h3>
<div class="return-to-shop">
    <a href="{% url 'gymapp:base' %}" class="btn return-btn">Torna al negozio</a>
</div>
{% endif %}
{% endblock %}

templates/partials/dettagli_prodotto.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Dettagli_Prodotto{% endblock %}
{% block hero_title %}Dettagli Prodotto{% endblock %}
{% block hero_image %}
<!-- Nessuna immagine -->
{% endblock %}
{% block products %}
<!-- Nessuna Prodotto -->
{% endblock %}

{% block content %}
<body>
    <header class="header">
        <nav class="navbar">
            <ul>
                <li><a href="{% url 'gymapp:base' %}">Homepage</a></li>
                <li><a href="{% url 'gymapp:contatti' %}">Contattaci</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="product-details">
            <div class="product-images">
                <h1 class="product-title">{{ p.title }}</h1>
                <img src="{{ p.image.url }}" alt="{{ p.title }}" class="main-image">
            </div>

            <div class="product-info">
                <p class="product-description">{{ p.description }}</p>
                <p class="product-price"><strong>Prezzo:</strong> &euro; {{ p.price }}</p>

                <div class="add-to-cart">
                    <form method="POST" action="{% url 'gymapp:add_to_cart' p.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="add_to_cart" value="true">
                        <button type="submit" class="button button-add-to-cart">Aggiungi al Carrello</button>
                    </form>
                </div>
            </div>
        </section>

        <section class="product-meta">
            <div class="meta-details">
                <h4>Details:</h4>
                <ul>
                    <li><strong>Type:</strong> {{ p.categ_type }}</li>
                    <li><strong>SKU:</strong> {{ p.sku }}</li>
                    <li><strong>Stock:</strong> {{ p.stock_count }} items in stock</li>
                </ul>
            </div>

            <div class="vendor-info">
                <h4>Fornitore:</h4>
                <p><a href="{% url 'gymapp:fornitore_list' p.vendor.vid %}">{{ p.vendor.title }}</p></a>
                <p>Address: {{ p.vendor.address }}</p>
                <p>Contact: {{ p.vendor.contact }}</p>
            </div>
        </section>
        <section class="related-products">
            <h3 class="related-title">Prodotti Correlati</h3>
            <div class="related-grid">
                {% if products %}
                    {% for p in products %}
                        <div class="related-card">
                            <div class="badge">{{ p.badge }}</div>
                            <img src="{{ p.image.url }}" alt="{{ p.title }}" class="related-image">
                            <h4 class="related-name">{{ p.title }}</h4>
                            <p><a href="{% url 'gymapp:fornitore_list' p.vendor.vid %}">{{ p.vendor.title }}</p></a>
                            <p class="related-price">€{{ p.price }}</p>
                            <a href="{% url 'gymapp:dettagli_prodotto' p.pid %}" class="related-details">Dettagli</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="no-products">Non ci sono altri prodotti correlati.</p>
                {% endif %}
            </div>
        </section>
        <section class="reviews">
            {% if user.is_authenticated %}
                <h3>Recensioni: ({{ reviews.count }})</h3>
                {% for r in reviews %}
                    <div class="review-box">
                        <div class="review-header">
                            <img src="{% static 'media/def_user.jpg' %}" alt="User Avatar" class="avatar"></a>
                            <p><strong>{{ r.user|title }}</strong> ha dato: {{ r.get_rating_display }}/★★★★★</p>
                        </div>
                        <div class="review-body">
                            <p>{{ r.review }}</p>
                            <p><em>{{ r.date|date:"d M, Y" }}</em></p>
                        </div>
                    </div>
                {% empty %}
                    <p>Non ci sono ancora recensioni per questo prodotto. Scrivi la prima!</p>
                {% endfor %}
            </section>
            <section class="add-review">
                <h3>Aggiungi una recensione</h3>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="add_review" value="true">
                    <div class="form-group">
                        <label for="review">Scrivi la tua recensione:</label>
                        {{ review_form.review }}
                    </div>
                    <div class="form-group">
                        <label for="rating">Valutazione:</label>
                        {{ review_form.rating }}
                    </div>
                    <button type="submit" class="btn-submit">Invia Recensione</button>
                </form>
            {% else %}
                <section class="login-prompt">
                    <p class="login-message">Devi effettuare il login per vedere le recensioni.</p>
                    <a href="{% url 'userauths:sign-in' %}" class="login-button">Effettua il Login</a>
                </section>
            {% endif %}
        </section>
    </main>
</body>
{% endblock %}

templates/partials/ricerca.html
{% extends 'partials/base.html' %}
{% block title %}Risultati della Ricerca{% endblock %}
{% block hero_title %}Risultati per "{{ query }}"{% endblock %}

{% block hero_image %}
<!-- Nessuna immagine -->
{% endblock %}
{% block products %}
<!-- Nessuna Prodotto -->
{% endblock %}
{% block content %}
<section class="search-results">
    <div class="search-header">
        <h2>Risultati della Ricerca</h2>
    </div>
        {% if products %}
        <div class="product-grid">
            {% for p in products %}
                <div class="product-card">
                    <img src="{{ p.image.url }}" alt="{{ p.title }}" style="max-width: 100px;"/>
                    <h3>{{ p.title }}</h3>
                    <p>{{ p.description }}</p>
                    <p><strong>Prezzo:</strong> €{{ p.price }}</p>
                    <a href="{% url 'gymapp:dettagli_prodotto' p.pid %}" class="details-button">Dettagli</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="no-results">Nessun prodotto trovato.</p>
    {% endif %}
</section>
{% endblock %}