GymCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gymapp.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gymapp/urls.py
from django.urls import path
from gymapp import views


app_name = "gymapp"

urlpatterns = [
    #Homepage
    path("", views.base, name='base'),

    #Prodotti
    path('manubri/', views.manubri, name='manubri'),
    path('bilancieri/', views.bilancieri, name='bilancieri'),
    path('dischi/', views.dischi, name='dischi'),
    path('collari/', views.collari, name='collari'),
    path('tapisrulant/', views.tapis, name='tapis'),
    path('vogatori/', views.vogatori, name='vogatori'),
    path('cyclette/', views.bike, name='cyclette'),
    path('unica/', views.unica, name='unica'),
    path('rack/', views.rack, name='rack' ),
    path('addome/', views.addome, name='addome'),
    path('lombare/', views.lombare, name='lombare'),
    path('panche/', views.panche, name='panche'),
    path('dettagli_prodotto/<pid>/', views.product_detail_view, name ='dettagli_prodotto'),

    #Menù
    path('contatti/', views.contatti, name='contatti'),  
    path('search/', views.search, name='search'),

    #Privacy
    path('privacy/', views.privacy, name='privacy'),

    #Fornitore
    path('fornitore/<vid>/', views.fornitore_list, name ='fornitore_list'),

    #Aggiungi Recensione
    path('product/<int:pid>/', views.product_detail_view, name='product_details'),

    #Carrello
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:pid>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:pk>/', views.update_cart_item, name='update_cart_item'),
    path('cart/remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),

    #Checkout
    path('checkout/', views.checkout_view, name='checkout'),

    #Pagamento
    path('payment_completed/', views.payment_completed_view, name='payment_completed'),
    path('payment_failed/', views.payment_failed_view, name='payment_failed'),


]



userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("user-view/", views.user_view, name="user-view"),

    path("profile/edit/", views.profile_update, name="profile-update"),

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Modello personalizzato per la gestione degli utenti, estendendo il modello predefinito di Django
# e aggiungendo campi extra come email univoca, biografia e flag per i fornitori
class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    is_fornitore = models.BooleanField(default=False)  # Campo per distinguere i fornitori

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email
    


#Modifica del Profilo Utente
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #Quando elimino un utente elimino anche il suo profilo
    image = models.ImageField(upload_to="image")
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio= models.CharField(max_length=200)
    phone = models.CharField(max_length=200) #+39 3491284782

    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"



#Permette ad ogni utente che si registra di avere la sua pagina di profilo
def create_user_profile (sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

# Modulo per la registrazione di un nuovo utente, estendendo il modulo di creazione utente predefinito di Django
class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']

# Modulo per la gestione del profilo utente, includendo campi con placeholder per facilitare la compilazione
class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))

    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
#from django.conf import settings
from .models import User, Profile
from django.contrib.auth.decorators import login_required
#User = settings.AUTH_USER_MODEL


# Registrazione.
def register_view(request):

    if request.method =="POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, il tuo account è stato creato correttamente.")
            new_user = authenticate(username = form.cleaned_data['email'],
                                    password = form.cleaned_data['password1']                        
            )
            login(request, new_user)
            return redirect("gymapp:base")


    else:
        print("L'utente non può essere registrato")
        form = UserRegisterForm()
    

    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)

#Login.
def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hai già fatto l'accesso")
        return redirect("gymapp:base")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            
            if user is not None:
                login(request, user)
                messages.success(request, f"Hai fatto l'accesso correttamente.")
                return redirect("gymapp:base")
            else:
                messages.warning(request, f"L'utente non esiste, crea un account. ")
                return redirect("gymapp:base")

        except:
            messages.warning(request, f"L'utente {email} non esiste.")
            return redirect("gymapp:base")


    return render(request, "userauths/sign-in.html")

#logout
def logout_view(request):
    logout(request)
    messages.success(request, f"Ti sei disconnesso")
    return redirect("gymapp:base")


@login_required
def user_view(request):
    user = request.user
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        # Aggiornamento delle informazioni utente
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')

        # Validazione e salvataggio
        if first_name and last_name and email:
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            user.save()
            messages.success(request, "Il tuo profilo è stato aggiornato con successo.")
        else:
            messages.error(request, "Tutti i campi sono obbligatori.")

    # Render della pagina del profilo
    context = {
        'profile':profile,
        'user': user,
    }
    return render(request, 'userauths/user-page.html', context)


def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile_save = form.save(commit=False)
            profile_save.user = request.user
            profile_save.save()
            messages.success(request, "Profilo aggiornato con successo")
            return redirect ("userauths:user-view")
    else:
        form = ProfileForm(instance=profile)


    context = {
        "form": form,
        "profile":profile
    }

    return render (request, "userauths/profile-edit.html",context)

templates/userauths/profile-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aggiorna Profilo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/userauths_css/user_styles.css' %}">
</head>
<body>
    <div class="profile-container">
        <div class="profile-header">
            <h1>Aggiorna Profilo</h1>
        </div>
        {% if form.errors %}
        <div class="alert-danger alert">
            <strong>{{ form.errors }}</strong>                   
        </div>
        {% endif %}
        <div class="profile-card">
            <div class="profile-image">
                {% if profile.image %}
                <img src="{{ profile.image.url }}" style="width: 150px; height: 150px;" alt="Immagine profilo">
                {% else %}
                <img src="{% static 'media/def_user.jpg' %}" alt="User Avatar" class="avatar"></a>
                {% endif %}
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    {{form.full_name}}
                </div>
                <div class="mb-3">
                    {{form.bio}}
                </div>
                <div class="mb-3">
                    {{form.phone}}
                </div>
                <div class="mb-3">
                    {{form.image}}
                </div>
                <button class="btn btn-success" type="submit">Salva Cambiamenti</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/userauths/sign-in.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            background-color: #1c1c1c;
            color: #fff;
            font-family: Arial, sans-serif;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .login-container {
            text-align: center;
            width: 100%;
            max-width: 400px;
            padding: 20px;
        }

        .logo {
            width: 80px;
            margin-bottom: 20px;
        }

        h1 {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        p {
            font-size: 14px;
            margin-bottom: 20px;
            color: #ccc;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        input[type="email"], input[type="password"] {
            background-color: #333;
            border: 1px solid #444;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        input::placeholder {
            color: #999;
        }

        a {
            color: #007bff;
            text-decoration: none;
            font-size: 14px;
        }

        a:hover {
            text-decoration: underline;
        }

        button {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            margin-top: 10px;
        }

        button:hover {
            background-color: #444;
        }

        .register-link {
            margin-top: 20px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <a href ="{% url 'gymapp:base' %}">
        <img src="/media/logo.jpg" alt="Logo GymShop" class="logo"></a>
        <h1>GYMSHOP LOGIN</h1>
        <p>Accedi per gestire i tuoi ordini, preferiti e molto altro.</p>
        <form method="POST" action="{% url 'userauths:sign-in' %}">
            {% csrf_token %}
            <input required type="email" name="email" placeholder="Email address" required>
            <input required type="password" name="password" placeholder="Password" required>
            <button type="submit">LOG IN</button>
        </form>
        <div class="register-link">
            <p>Non hai un account? <a href="{% url 'userauths:sign-up' %}">Registrati</a></p>
        </div>
    </div>
</body>
</html>

templates/userauths/sign-up.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrati</title>
    <style>
        body {
            background-color: #1c1c1c;
            color: #fff;
            font-family: Arial, sans-serif;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .register-container {
            text-align: center;
            width: 100%;
            max-width: 400px;
            padding: 20px;
        }

        .logo {
            width: 80px;
            margin-bottom: 20px;
        }

        h1 {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        p {
            font-size: 14px;
            margin-bottom: 20px;
            color: #ccc;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        input[type="text"], input[type="email"], input[type="password"], input[type="number"] {
            background-color: #333;
            border: 1px solid #444;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        input::placeholder {
            color: #999;
        }

        a {
            color: #007bff;
            text-decoration: none;
            font-size: 14px;
        }

        a:hover {
            text-decoration: underline;
        }

        button {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            margin-top: 10px;
        }

        button:hover {
            background-color: #444;
        }

        .login-link {
            margin-top: 20px;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="register-container">
        <a href ="{% url 'gymapp:base' %}">
        <img src="/media/logo.jpg" alt="Logo GymShop" class="logo"></a>
        <h1>Registrati su GymShop</h1>
        <p>Crea un account per iniziare a gestire i tuoi ordini e preferiti.</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Registrati</button>
            <div class="login-link">
                <p>Hai già un account? <a href="{% url 'userauths:sign-in' %}">Accedi</a></p>
            </div>
        </form>
    </div>
</body>
</html>

templates/userauths/user-page.html
{% load static %}
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profilo Utente</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/userauths_css/user_styles.css' %}">
</head>
<body>
    <div class="profile-container">
        <div class="profile-header">
            <h1>Profilo Utente</h1>
        </div>
        <div class="profile-card">
            <div class="profile-image">
                {% if profile.image %}
                <img src="{{ profile.image.url }}" style="width: 150px; height: 150px;" alt="Immagine profilo">
                {% else %}
                <img src="{% static 'media/def_user.jpg' %}" alt="User Avatar" class="avatar"></a>
                {% endif %}
            </div>
            <div class="profile-details">
                <p><strong>Nome utente -<input class="mb-2"type="text" value="{{ profile.full_name|title }}"></strong></p>
                <p><strong>Bio - <input class="mb-2"type="text" value="{{ profile.bio }}"></strong></p>
                <p><strong>Numero - <input class="mb-2"type="text" value="{{ profile.phone }}"></strong></p>
                {% if profile.user.is_fornitore == True %}
                    <p><strong>Fornitore</strong><i class="fas fa-check-cicle">✅</i></p>
                {% else %}
                    <p><strong>Non sei fornitore</strong><i class="fas fa-x">❌</i></p>
                {%  endif %}
            </div>
            <div class="profile-dates">
                <p><strong>Data di registrazione:{{ user.date_joined|date:"d/m/Y H:i" }}</strong></p>
                <p><strong>Ultimo accesso:{{ user.last_login|date:"d/m/Y H:i" }}</strong></p>
            </div>
            <div class="profile-actions">
                <a href="{% url 'userauths:sign-out' %}" class="btn logout">Esci</a>
                <a href ="{% url 'gymapp:base' %}" class="btn home">Torna alla Home</a>
                <a href ="{% url 'userauths:profile-update'%}" class="btn btn-success">Modifica profilo</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>